import '../domain/entity/attendance_entity.dart';

List<AttendanceEntity> attendances = [
  AttendanceEntity(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: false,
    number: 1,
    id: 1,
  ),
  AttendanceEntity(
    cid: 16,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: true,
    number: 1,
    id: 2,
  ),
  AttendanceEntity(
    cid: 11,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: true,
    number: 1,
    id: 3,
  ),
  AttendanceEntity(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: false,
    number: 1,
    id: 4,
  ),
  AttendanceEntity(
    cid: 34,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: true,
    number: 1,
    id: 324,
  ),
  AttendanceEntity(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: false,
    number: 1,
    id: 543,
  ),
  AttendanceEntity(
    cid: 24,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: true,
    number: 1,
    id: 1243,
  ),
  AttendanceEntity(
    cid: 15,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: false,
    number: 1,
    id: 12,
  ),
];
