import '../../../../model/attendance.dart';

List<Attendance> attendances = [
  Attendance(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: false,
    number: 1,
    id: 1,
  ),
  Attendance(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: true,
    number: 1,
    id: 2,
  ),
  Attendance(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: true,
    number: 1,
    id: 3,
  ),
  Attendance(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: false,
    number: 1,
    id: 4,
  ),
  Attendance(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: true,
    number: 1,
    id: 324,
  ),
  Attendance(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: false,
    number: 1,
    id: 543,
  ),
  Attendance(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: true,
    number: 1,
    id: 1243,
  ),
  Attendance(
    cid: 14,
    createdTime: DateTime.now(),
    description: 'Atendimento realizado devido ao....',
    title: 'Atendimento remoto',
    isUrgency: false,
    number: 1,
    id: 12,
  ),
];
